# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.33.42"
  config.vm.boot_timeout = 600

  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.name = "ElasticSearch2"
    # From https://coderwall.com/p/n2y79g
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  # RabbitMQ
  config.vm.network :forwarded_port, guest: 15672, host: 15672
  config.vm.network :forwarded_port, guest: 55672, host: 55672
  config.vm.network :forwarded_port, guest: 5672, host: 5672

  # ElasticSearch
  config.vm.network :forwarded_port, guest: 9200, host: 9200

  # Kibana v4
  config.vm.network :forwarded_port, guest: 5601, host: 5601
end
